/**
 * Deferred shell markup (injected on init for smaller initial HTML download + parse).
 * Generated by scripts/extract-index-slices.mjs — do not edit by hand without re-running.
 */
export const TEMPLATE_REGISTRATION_STUDENT_INNER = ``;

export const TEMPLATE_REGISTRATION_TEACHER_INNER = ``;

export const TEMPLATE_AI_MODAL = ``;

export const TEMPLATE_LEGAL_MODAL = ``;

export const TEMPLATE_EDIT_STUDENT_MODAL = ``;

export const TEMPLATE_CHANGE_ROLE_MODAL = ``;
