/**
 * Deferred shell markup (injected on init for smaller initial HTML download + parse).
 * Generated by scripts/extract-index-slices.mjs — do not edit by hand without re-running.
 */
export const TEMPLATE_REGISTRATION_STUDENT_INNER = `              <div
                class="glass-effect lms-reg-shell p-4 sm:p-6 max-md:max-h-[min(calc(100dvh-6.5rem),36rem)] max-md:overflow-y-auto max-md:overscroll-contain"
              >
                <h3 class="lms-reg-page-title">Student Registration</h3>

                
                <div class="lms-info-callout">
                  <h4 class="lms-info-callout-title">
                    <svg
                      class="w-4 h-4 sm:w-5 sm:h-5 shrink-0"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                      ></path>
                    </svg>
                    Registration Instructions
                  </h4>
                  <p class="lms-info-callout-body">
                    Fill in the student information below to register a new student in the system.
                    All fields marked with <span class="text-red-600 dark:text-red-400">*</span>
                    are required.
                  </p>
                </div>

                
                <form id="student-registration-form" class="space-y-3 sm:space-y-6 min-w-0">
                  <div class="grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-6 min-w-0">
                    
                    <div>
                      <label class="lms-form-label">
                        Student Name <span class="text-red-600 dark:text-red-400">*</span>
                      </label>
                      <input
                        type="text"
                        name="studentName"
                        required
                        placeholder="John Smith"
                        class="lms-form-input"
                      />
                    </div>

                    
                    <div class="min-w-0">
                      <label class="lms-form-label"> Membership ID </label>
                      <input
                        type="text"
                        name="memberId"
                        placeholder="STU001 (optional)"
                        class="lms-form-input"
                      />
                    </div>

                    
                    <div class="min-w-0">
                      <label class="lms-form-label">
                        Year of Birth <span class="text-red-600 dark:text-red-400">*</span>
                      </label>
                      <input
                        type="number"
                        name="yearOfBirth"
                        required
                        min="1990"
                        max="2025"
                        placeholder="2010"
                        class="lms-form-input"
                      />
                    </div>

                    
                    <div class="min-w-0">
                      <label class="lms-form-label">
                        Contact Phone <span class="text-red-600 dark:text-red-400">*</span>
                      </label>
                      <input
                        type="tel"
                        name="contactPhone"
                        required
                        placeholder="+1 (555) 123-4567"
                        class="lms-form-input"
                      />
                    </div>

                    
                    <div class="min-w-0">
                      <label class="lms-form-label">
                        Contact Email <span class="text-red-600 dark:text-red-400">*</span>
                      </label>
                      <input
                        type="email"
                        name="contactEmail"
                        required
                        placeholder="parent@example.com"
                        class="lms-form-input"
                      />
                    </div>

                    
                    <div class="min-w-0 md:col-span-2">
                      <label class="lms-form-label">
                        Link to Student Account
                        <span class="text-red-600 dark:text-red-400">*</span>
                      </label>

                      
                      <div id="dropdown-method" class="space-y-2 min-w-0">
                        <div class="flex flex-col sm:flex-row gap-2 items-stretch min-w-0">
                          <div
                            id="student-account-dropdown"
                            class="account-dropdown flex-1 relative min-w-0"
                          >
                            <div
                              class="account-dropdown-trigger lms-account-trigger"
                              tabindex="0"
                              role="combobox"
                              aria-expanded="false"
                              aria-haspopup="listbox"
                              aria-label="Link to student account"
                            >
                              <span class="account-dropdown-value text-left truncate"
                                >-- Select Registered Account --</span
                              >
                              <svg
                                class="w-5 h-5 text-slate-500 dark:text-dark-400 flex-shrink-0 ml-2"
                                fill="none"
                                stroke="currentColor"
                                viewBox="0 0 24 24"
                              >
                                <path
                                  stroke-linecap="round"
                                  stroke-linejoin="round"
                                  stroke-width="2"
                                  d="M19 9l-7 7-7-7"
                                ></path>
                              </svg>
                            </div>
                            <div
                              class="account-dropdown-panel lms-dropdown-panel absolute left-0 right-0 top-full mt-1 z-50 hide"
                            >
                              <input
                                type="text"
                                class="account-dropdown-search lms-dropdown-search"
                                placeholder="Search by email..."
                                autocomplete="off"
                                aria-label="Search accounts by email"
                              />
                              <div
                                class="account-dropdown-list max-h-60 overflow-y-auto py-1"
                                role="listbox"
                              ></div>
                            </div>
                          </div>
                          <button
                            type="button"
                            id="refresh-accounts-btn"
                            class="lms-btn-icon-refresh"
                            title="Refresh accounts list"
                          >
                            <svg
                              class="w-5 h-5"
                              fill="none"
                              stroke="currentColor"
                              viewBox="0 0 24 24"
                            >
                              <path
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
                              ></path>
                            </svg>
                          </button>
                        </div>
                        <button type="button" id="use-manual-uid-btn" class="lms-inline-link">
                          Or enter UID manually (Cloud Functions not deployed?)
                        </button>
                      </div>

                      
                      <div id="manual-method" class="space-y-2 hide">
                        <input
                          type="text"
                          id="manual-student-uid"
                          placeholder="Paste Firebase Auth UID here"
                          class="lms-form-input font-mono"
                        />
                        <button type="button" id="use-dropdown-btn" class="lms-inline-link">
                          Back to dropdown
                        </button>
                        <div class="lms-warn-hint">
                          <strong>How to get UID:</strong>
                          <ol class="ml-3 sm:ml-4 mt-1 list-decimal space-y-0.5">
                            <li>
                              Go to
                              <a
                                href="https://console.firebase.google.com"
                                target="_blank"
                                class="lms-inline-link"
                                >Firebase Console</a
                              >
                              → your project → Authentication → Users
                            </li>
                            <li>Find student's email in Users list</li>
                            <li>Copy their "User UID"</li>
                            <li>Paste it above</li>
                          </ol>
                        </div>
                      </div>

                      
                      <input type="hidden" name="studentUid" id="final-student-uid" required />
                    </div>
                  </div>

                  
                  <div class="min-w-0">
                    <label class="lms-form-label"> Additional Notes (Optional) </label>
                    <textarea
                      name="notes"
                      rows="2"
                      placeholder="Any additional information about the student..."
                      class="lms-form-textarea"
                    ></textarea>
                  </div>

                  
                  <div
                    id="registration-error"
                    class="text-red-600 dark:text-red-400 text-xs sm:text-sm hide"
                  ></div>

                  
                  <div
                    id="registration-success"
                    class="text-green-700 dark:text-green-400 text-xs sm:text-sm hide"
                  ></div>

                  
                  <button
                    type="submit"
                    class="w-full min-h-[48px] py-3 sm:py-4 px-4 sm:px-6 bg-gradient-to-r from-primary-500 to-primary-600 text-white font-semibold rounded-lg hover:from-primary-600 hover:to-primary-700 transition-all shadow-lg text-base sm:text-lg"
                  >
                    Register Student
                  </button>
                </form>
              </div>

              
              <div class="glass-effect lms-reg-shell p-4 sm:p-6 md:p-8 mt-4 md:mt-6 md:rounded-3xl">
                <h3 class="lms-reg-bulk-title">
                  <svg
                    class="w-6 h-6 sm:w-7 sm:h-7 text-primary-700 dark:text-primary-400 shrink-0"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    aria-hidden="true"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"
                    />
                  </svg>
                  Bulk CSV Upload
                </h3>
                <p class="text-xs sm:text-sm text-on-surface-muted mb-4 leading-relaxed">
                  Upload a CSV to register multiple students. Rows are matched to existing
                  <span class="font-medium text-slate-800 dark:text-dark-200">student</span>
                  accounts by display name or email username when possible. Admins may import rows
                  with no match as roster-only records; teachers must have a matching account per
                  row.
                </p>
                <div class="mb-4 flex flex-wrap gap-3">
                  <button type="button" id="csv-download-template-btn" class="lms-csv-template-btn">
                    <svg
                      class="w-4 h-4 shrink-0"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                      aria-hidden="true"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                      />
                    </svg>
                    Download CSV Template
                  </button>
                </div>
                <div
                  id="csv-drop-zone"
                  class="relative border-2 border-dashed border-slate-300 rounded-xl sm:rounded-2xl p-4 sm:p-8 text-center cursor-pointer hover:border-primary-500 hover:bg-primary-500/5 dark:border-dark-600 dark:hover:border-primary-500/70 transition-all group min-h-[8rem]"
                >
                  <input
                    type="file"
                    id="csv-file-input"
                    accept=".csv,text/csv"
                    class="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10"
                    aria-label="Choose CSV file"
                  />
                  <div class="pointer-events-none">
                    <svg
                      class="w-10 h-10 sm:w-12 sm:h-12 mx-auto mb-3 text-slate-400 group-hover:text-primary-600 dark:text-dark-500 dark:group-hover:text-primary-400 transition-colors"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                      aria-hidden="true"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="1.5"
                        d="M9 13h6m-3-3v6m5 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                      />
                    </svg>
                    <p class="text-slate-800 dark:text-dark-200 font-medium text-sm sm:text-base">
                      Drag &amp; drop your CSV file here
                    </p>
                    <p class="text-slate-500 dark:text-dark-500 text-xs sm:text-sm mt-1">
                      or click to browse
                    </p>
                  </div>
                </div>
                <div id="csv-preview-container" class="hide mt-4">
                  <div class="flex flex-wrap items-center justify-between gap-2 mb-3">
                    <h4
                      class="text-slate-900 dark:text-dark-100 font-semibold text-sm sm:text-base flex items-center gap-2"
                    >
                      <svg
                        class="w-5 h-5 text-green-600 dark:text-green-400 shrink-0"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                        aria-hidden="true"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          stroke-width="2"
                          d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                        />
                      </svg>
                      Preview (<span id="csv-row-count">0</span> students)
                    </h4>
                    <button
                      type="button"
                      id="csv-clear-btn"
                      class="text-sm text-red-600 hover:text-red-800 dark:text-red-400 dark:hover:text-red-300 underline min-h-[44px] px-1"
                    >
                      Clear
                    </button>
                  </div>
                  <div
                    class="overflow-x-auto max-h-72 overflow-y-auto rounded-xl border border-slate-200/90 dark:border-dark-600"
                  >
                    <table class="w-full text-xs sm:text-sm min-w-[640px]">
                      <thead
                        class="sticky top-0 z-[1] border-b border-slate-200 bg-slate-50/95 backdrop-blur-sm dark:border-dark-600 dark:bg-dark-900/95"
                      >
                        <tr>
                          <th
                            class="py-2 px-3 text-left text-slate-700 dark:text-dark-300 font-semibold"
                          >
                            #
                          </th>
                          <th
                            class="py-2 px-3 text-left text-slate-700 dark:text-dark-300 font-semibold"
                          >
                            Name
                          </th>
                          <th
                            class="py-2 px-3 text-left text-slate-700 dark:text-dark-300 font-semibold"
                          >
                            Member ID
                          </th>
                          <th
                            class="py-2 px-3 text-left text-slate-700 dark:text-dark-300 font-semibold"
                          >
                            Year of Birth
                          </th>
                          <th
                            class="py-2 px-3 text-left text-slate-700 dark:text-dark-300 font-semibold"
                          >
                            Phone
                          </th>
                          <th
                            class="py-2 px-3 text-left text-slate-700 dark:text-dark-300 font-semibold"
                          >
                            Email
                          </th>
                          <th
                            class="py-2 px-3 text-center text-slate-700 dark:text-dark-300 font-semibold"
                          >
                            Status
                          </th>
                        </tr>
                      </thead>
                      <tbody id="csv-preview-body"></tbody>
                    </table>
                  </div>
                  <div
                    id="csv-error-summary"
                    class="hide mt-3 p-3 rounded-lg bg-red-500/10 border border-red-500/30 text-red-400 text-xs sm:text-sm"
                    role="alert"
                  ></div>
                  <button
                    type="button"
                    id="csv-upload-btn"
                    class="w-full mt-4 min-h-[48px] py-3.5 px-6 bg-gradient-to-r from-primary-500 to-primary-600 text-white font-semibold rounded-lg hover:from-primary-600 hover:to-primary-700 transition-all shadow-lg"
                  >
                    <span class="flex items-center justify-center gap-2">
                      <svg
                        class="w-5 h-5 shrink-0"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                        aria-hidden="true"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          stroke-width="2"
                          d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"
                        />
                      </svg>
                      Register All Students
                    </span>
                  </button>
                  <div id="csv-progress-container" class="hide mt-3">
                    <div class="flex items-center justify-between text-xs sm:text-sm mb-1">
                      <span class="text-slate-600 dark:text-dark-300" id="csv-progress-label"
                        >Registering...</span
                      >
                      <span
                        class="text-primary-700 dark:text-primary-400 font-semibold"
                        id="csv-progress-pct"
                        >0%</span
                      >
                    </div>
                    <div class="h-2 bg-slate-200 dark:bg-dark-700 rounded-full overflow-hidden">
                      <div
                        id="csv-progress-bar"
                        class="h-full bg-gradient-to-r from-primary-500 to-primary-400 rounded-full transition-all duration-300"
                        style="width: 0%"
                      ></div>
                    </div>
                  </div>
                </div>
              </div>

              
              <div class="glass-effect lms-reg-shell p-4 sm:p-6 mt-0 md:mt-6">
                <h3 class="lms-reg-section-title">Registered Students</h3>
                <div class="mb-3 sm:mb-4 min-w-0">
                  <input
                    type="text"
                    id="registered-students-search"
                    placeholder="Search by Member ID, name, or email..."
                    class="lms-form-input"
                    aria-label="Search registered students"
                  />
                </div>
                <div class="overflow-x-auto -mx-1 px-1 sm:mx-0 sm:px-0 touch-pan-x">
                  <table class="w-full min-w-[520px] text-xs sm:text-sm">
                    <thead>
                      <tr
                        class="border-b border-slate-200 bg-slate-50/90 dark:border-dark-600 dark:bg-transparent"
                      >
                        <th
                          class="text-left py-2 sm:py-3 px-2 sm:px-4 text-slate-700 dark:text-dark-200 font-semibold whitespace-nowrap"
                        >
                          Member ID
                        </th>
                        <th
                          class="text-left py-2 sm:py-3 px-2 sm:px-4 text-slate-700 dark:text-dark-200 font-semibold"
                        >
                          Name
                        </th>
                        <th
                          class="text-center py-2 sm:py-3 px-2 sm:px-4 text-slate-700 dark:text-dark-200 font-semibold whitespace-nowrap"
                        >
                          Year
                        </th>
                        <th
                          class="text-left py-2 sm:py-3 px-2 sm:px-4 text-slate-700 dark:text-dark-200 font-semibold"
                        >
                          Contact
                        </th>
                        <th
                          class="text-center py-2 sm:py-3 px-2 sm:px-4 text-slate-700 dark:text-dark-200 font-semibold whitespace-nowrap"
                        >
                          Actions
                        </th>
                      </tr>
                    </thead>
                    <tbody id="registered-students-table-body">
                      <tr>
                        <td colspan="5" class="text-center py-8 text-slate-600 dark:text-dark-300">
                          No students registered yet
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>`;

export const TEMPLATE_REGISTRATION_TEACHER_INNER = `              <div
                class="glass-effect lms-reg-shell p-4 sm:p-6 max-md:max-h-[min(calc(100dvh-6.5rem),36rem)] max-md:overflow-y-auto max-md:overscroll-contain"
              >
                <h3 class="lms-reg-page-title">Teacher Registration</h3>

                
                <div class="lms-info-callout">
                  <h4 class="lms-info-callout-title">
                    <svg
                      class="w-4 h-4 sm:w-5 sm:h-5 shrink-0"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                      ></path>
                    </svg>
                    Registration Instructions
                  </h4>
                  <p class="lms-info-callout-body">
                    Fill in the teacher information below to register a new teacher in the system.
                    All fields marked with <span class="text-red-600 dark:text-red-400">*</span> are
                    required.
                  </p>
                </div>

                
                <form id="teacher-registration-form" class="space-y-3 sm:space-y-6 min-w-0">
                  <div class="grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-6 min-w-0">
                    
                    <div class="min-w-0">
                      <label class="lms-form-label">
                        Teacher Name <span class="text-red-600 dark:text-red-400">*</span>
                      </label>
                      <input
                        type="text"
                        name="teacherName"
                        required
                        placeholder="Jane Doe"
                        class="lms-form-input"
                      />
                    </div>

                    
                    <div class="min-w-0">
                      <label class="lms-form-label"> Membership ID </label>
                      <input
                        type="text"
                        name="teacherMemberId"
                        placeholder="TCH001 (optional)"
                        class="lms-form-input"
                      />
                    </div>

                    
                    <div class="min-w-0">
                      <label class="lms-form-label"> Year of Birth </label>
                      <input
                        type="number"
                        name="teacherYearOfBirth"
                        min="1950"
                        max="2010"
                        placeholder="1985 (optional)"
                        class="lms-form-input"
                      />
                    </div>

                    
                    <div class="min-w-0">
                      <label class="lms-form-label">
                        Contact Phone <span class="text-red-600 dark:text-red-400">*</span>
                      </label>
                      <input
                        type="tel"
                        name="teacherPhone"
                        required
                        placeholder="+1 (555) 123-4567"
                        class="lms-form-input"
                      />
                    </div>

                    
                    <div class="min-w-0">
                      <label class="lms-form-label">
                        Contact Email <span class="text-red-600 dark:text-red-400">*</span>
                      </label>
                      <input
                        type="email"
                        name="teacherEmail"
                        required
                        placeholder="teacher@example.com"
                        class="lms-form-input"
                      />
                    </div>

                    
                    <div class="min-w-0 md:col-span-2">
                      <label class="lms-form-label">
                        Link to Teacher Account
                        <span class="text-red-600 dark:text-red-400">*</span>
                      </label>
                      <div id="teacher-dropdown-method" class="space-y-2 min-w-0">
                        <div class="flex flex-col sm:flex-row gap-2 items-stretch min-w-0">
                          <div
                            id="teacher-account-dropdown"
                            class="account-dropdown flex-1 relative min-w-0"
                          >
                            <div
                              class="account-dropdown-trigger lms-account-trigger"
                              tabindex="0"
                              role="combobox"
                              aria-expanded="false"
                              aria-haspopup="listbox"
                              aria-label="Link to teacher account"
                            >
                              <span class="account-dropdown-value text-left truncate"
                                >-- Select Registered Account --</span
                              >
                              <svg
                                class="w-5 h-5 text-slate-500 dark:text-dark-400 flex-shrink-0 ml-2"
                                fill="none"
                                stroke="currentColor"
                                viewBox="0 0 24 24"
                              >
                                <path
                                  stroke-linecap="round"
                                  stroke-linejoin="round"
                                  stroke-width="2"
                                  d="M19 9l-7 7-7-7"
                                ></path>
                              </svg>
                            </div>
                            <div
                              class="account-dropdown-panel lms-dropdown-panel absolute left-0 right-0 top-full mt-1 z-50 hide"
                            >
                              <input
                                type="text"
                                class="account-dropdown-search lms-dropdown-search"
                                placeholder="Search by email..."
                                autocomplete="off"
                                aria-label="Search accounts by email"
                              />
                              <div
                                class="account-dropdown-list max-h-60 overflow-y-auto py-1"
                                role="listbox"
                              ></div>
                            </div>
                          </div>
                          <button
                            type="button"
                            id="refresh-teacher-accounts-btn"
                            class="lms-btn-icon-refresh"
                            title="Refresh accounts list"
                          >
                            <svg
                              class="w-5 h-5"
                              fill="none"
                              stroke="currentColor"
                              viewBox="0 0 24 24"
                            >
                              <path
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
                              ></path>
                            </svg>
                          </button>
                        </div>
                        <button
                          type="button"
                          id="use-manual-teacher-uid-btn"
                          class="lms-inline-link"
                        >
                          Or enter UID manually
                        </button>
                      </div>
                      <div id="teacher-manual-method" class="space-y-2 hide">
                        <input
                          type="text"
                          id="manual-teacher-uid"
                          placeholder="Paste Firebase Auth UID here"
                          class="lms-form-input font-mono"
                        />
                        <button type="button" id="use-dropdown-teacher-btn" class="lms-inline-link">
                          Back to dropdown
                        </button>
                        <div class="lms-warn-hint">
                          <strong>How to get UID:</strong> Firebase Console → Authentication → copy
                          User UID.
                        </div>
                      </div>
                      <input type="hidden" name="teacherUid" id="final-teacher-uid" required />
                    </div>
                  </div>

                  
                  <div class="min-w-0">
                    <label class="lms-form-label"> Additional Notes (Optional) </label>
                    <textarea
                      name="teacherNotes"
                      rows="2"
                      placeholder="Any additional information about the teacher..."
                      class="lms-form-textarea"
                    ></textarea>
                  </div>

                  <div
                    id="teacher-registration-error"
                    class="text-red-600 dark:text-red-400 text-xs sm:text-sm hide"
                  ></div>
                  <div
                    id="teacher-registration-success"
                    class="text-green-700 dark:text-green-400 text-xs sm:text-sm hide"
                  ></div>

                  <button
                    type="submit"
                    class="w-full min-h-[48px] py-3 sm:py-4 px-4 sm:px-6 bg-gradient-to-r from-primary-500 to-primary-600 text-white font-semibold rounded-lg hover:from-primary-600 hover:to-primary-700 transition-all shadow-lg text-base sm:text-lg"
                  >
                    Register Teacher
                  </button>
                </form>
              </div>

              
              <div class="glass-effect lms-reg-shell p-4 sm:p-6 mt-0 md:mt-6">
                <h3 class="lms-reg-section-title">Registered Teachers</h3>
                <div class="mb-3 sm:mb-4 min-w-0">
                  <input
                    type="text"
                    id="registered-teachers-search"
                    placeholder="Search by Member ID, name, or email..."
                    class="lms-form-input"
                    aria-label="Search registered teachers"
                  />
                </div>
                <div class="overflow-x-auto -mx-1 px-1 sm:mx-0 sm:px-0 touch-pan-x">
                  <table class="w-full min-w-[520px] text-xs sm:text-sm">
                    <thead>
                      <tr
                        class="border-b border-slate-200 bg-slate-50/90 dark:border-dark-600 dark:bg-transparent"
                      >
                        <th
                          class="text-left py-2 sm:py-3 px-2 sm:px-4 text-slate-700 dark:text-dark-200 font-semibold whitespace-nowrap"
                        >
                          Member ID
                        </th>
                        <th
                          class="text-left py-2 sm:py-3 px-2 sm:px-4 text-slate-700 dark:text-dark-200 font-semibold"
                        >
                          Name
                        </th>
                        <th
                          class="text-center py-2 sm:py-3 px-2 sm:px-4 text-slate-700 dark:text-dark-200 font-semibold whitespace-nowrap"
                        >
                          Year
                        </th>
                        <th
                          class="text-left py-2 sm:py-3 px-2 sm:px-4 text-slate-700 dark:text-dark-200 font-semibold"
                        >
                          Contact
                        </th>
                        <th
                          class="text-center py-2 sm:py-3 px-2 sm:px-4 text-slate-700 dark:text-dark-200 font-semibold whitespace-nowrap"
                        >
                          Actions
                        </th>
                      </tr>
                    </thead>
                    <tbody id="registered-teachers-table-body">
                      <tr>
                        <td colspan="5" class="text-center py-8 text-slate-600 dark:text-dark-300">
                          No teachers registered yet
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>`;

export const TEMPLATE_AI_MODAL = `    <div
      id="ai-modal"
      class="lms-fixed-overlay-safe fixed inset-0 bg-dark-900/85 backdrop-blur-md flex items-center justify-center z-50 hide"
      aria-hidden="true"
    >
      <div
        id="ai-modal-panel"
        class="lms-modal-surface glass-effect rounded-2xl p-8 max-w-2xl w-full max-h-[80vh] overflow-y-auto shadow-2xl shadow-black/40"
        role="dialog"
        aria-modal="true"
        aria-labelledby="ai-modal-title"
      >
        <div class="flex justify-between items-start mb-4">
          <h3 id="ai-modal-title" class="text-2xl font-bold text-white">AI Results</h3>
          <button
            type="button"
            id="ai-modal-close"
            class="modal-close-trigger p-2 rounded-lg hover:bg-dark-700 transition-all"
            aria-label="Close dialog"
          >
            <svg
              class="w-6 h-6 text-dark-300"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M6 18L18 6M6 6l12 12"
              ></path>
            </svg>
          </button>
        </div>
        <div id="ai-modal-content" class="text-dark-200 prose max-w-none dark:prose-invert"></div>
      </div>
    </div>`;

export const TEMPLATE_LEGAL_MODAL = `    <div
      id="legal-modal"
      class="lms-fixed-overlay-safe fixed inset-0 z-[60] hide flex items-center justify-center backdrop-blur-md"
      aria-hidden="true"
    >
      <div
        id="legal-modal-backdrop"
        class="absolute inset-0 z-0"
        data-app-theme="dark"
        aria-hidden="true"
      ></div>
      <div
        id="legal-modal-panel"
        class="lms-modal-surface relative z-10 w-full max-w-2xl max-h-[85vh] flex flex-col rounded-2xl border border-slate-200 dark:border-slate-700 p-6 shadow-2xl"
        role="dialog"
        aria-modal="true"
        aria-labelledby="legal-modal-title"
        data-app-theme="dark"
      >
        <div class="flex justify-between items-start gap-4 mb-4 flex-shrink-0">
          <h3
            id="legal-modal-title"
            class="text-xl font-bold text-slate-900 dark:text-slate-100"
            data-app-theme="dark"
          >
            Privacy Policy
          </h3>
          <button
            type="button"
            id="legal-modal-close-x"
            class="p-2 rounded-lg transition-colors text-slate-600 hover:bg-slate-200 dark:text-slate-400 dark:hover:bg-slate-800"
            aria-label="Close"
          >
            <svg
              class="w-5 h-5"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              aria-hidden="true"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M6 18L18 6M6 6l12 12"
              ></path>
            </svg>
          </button>
        </div>
        <div
          id="legal-modal-body"
          class="overflow-y-auto flex-1 text-sm leading-relaxed pr-1 min-h-0"
        ></div>
        <div
          class="mt-6 flex justify-end flex-shrink-0 pt-2 border-t border-slate-200 dark:border-slate-700"
        >
          <button
            type="button"
            id="legal-modal-close"
            class="px-6 py-2.5 rounded-lg font-semibold bg-primary-500 hover:bg-primary-600 text-white transition-colors shadow-lg shadow-primary-500/20"
          >
            Close
          </button>
        </div>
      </div>
    </div>`;

export const TEMPLATE_EDIT_STUDENT_MODAL = `    <div
      id="edit-student-modal"
      class="lms-fixed-overlay-safe fixed inset-0 bg-dark-900/85 backdrop-blur-md flex items-center justify-center z-50 hide"
      aria-hidden="true"
    >
      <div
        id="edit-student-modal-panel"
        class="lms-modal-surface glass-effect rounded-2xl p-8 max-w-lg w-full max-h-[90vh] overflow-y-auto shadow-2xl shadow-black/35"
        role="dialog"
        aria-modal="true"
        aria-labelledby="edit-student-modal-title"
      >
        <div class="flex justify-between items-start mb-4">
          <h3 id="edit-student-modal-title" class="text-2xl font-bold text-white">Edit Student</h3>
          <button
            type="button"
            id="edit-student-modal-close"
            class="p-2 rounded-lg hover:bg-dark-700 transition-all"
            aria-label="Close"
          >
            <svg
              class="w-6 h-6 text-dark-300"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M6 18L18 6M6 6l12 12"
              ></path>
            </svg>
          </button>
        </div>
        <form id="edit-student-form" class="space-y-4">
          <input type="hidden" id="edit-student-id" name="studentId" />
          <div>
            <label class="block text-dark-200 text-sm font-semibold mb-1">Name</label>
            <input
              type="text"
              id="edit-student-name"
              name="name"
              required
              class="w-full px-4 py-3 rounded-lg bg-dark-800 border border-dark-600 text-white focus:outline-none focus:border-primary-500 input-glow transition-all"
            />
          </div>
          <div>
            <label class="block text-dark-200 text-sm font-semibold mb-1">Member ID</label>
            <input
              type="text"
              id="edit-student-memberId"
              name="memberId"
              class="w-full px-4 py-3 rounded-lg bg-dark-800 border border-dark-600 text-white focus:outline-none focus:border-primary-500 input-glow transition-all"
            />
          </div>
          <div>
            <label class="block text-dark-200 text-sm font-semibold mb-1">Year of Birth</label>
            <input
              type="number"
              id="edit-student-yearOfBirth"
              name="yearOfBirth"
              min="1950"
              max="2015"
              class="w-full px-4 py-3 rounded-lg bg-dark-800 border border-dark-600 text-white focus:outline-none focus:border-primary-500 input-glow transition-all"
            />
          </div>
          <div>
            <label class="block text-dark-200 text-sm font-semibold mb-1">Contact Phone</label>
            <input
              type="tel"
              id="edit-student-contactPhone"
              name="contactPhone"
              required
              class="w-full px-4 py-3 rounded-lg bg-dark-800 border border-dark-600 text-white focus:outline-none focus:border-primary-500 input-glow transition-all"
            />
          </div>
          <div>
            <label class="block text-dark-200 text-sm font-semibold mb-1">Contact Email</label>
            <input
              type="email"
              id="edit-student-contactEmail"
              name="contactEmail"
              required
              class="w-full px-4 py-3 rounded-lg bg-dark-800 border border-dark-600 text-white focus:outline-none focus:border-primary-500 input-glow transition-all"
            />
          </div>
          <div>
            <label class="block text-dark-200 text-sm font-semibold mb-1">Notes</label>
            <textarea
              id="edit-student-notes"
              name="notes"
              rows="2"
              class="w-full px-4 py-3 rounded-lg bg-dark-800 border border-dark-600 text-white focus:outline-none focus:border-primary-500 input-glow transition-all"
            ></textarea>
          </div>
          <div class="flex gap-3 pt-2">
            <button
              type="submit"
              class="flex-1 py-3 px-4 bg-primary-500 hover:bg-primary-600 text-white font-semibold rounded-lg transition-all"
            >
              Save
            </button>
            <button
              type="button"
              id="edit-student-cancel"
              class="py-3 px-4 bg-dark-700 hover:bg-dark-600 text-white rounded-lg transition-all"
            >
              Cancel
            </button>
          </div>
        </form>
      </div>
    </div>`;

export const TEMPLATE_CHANGE_ROLE_MODAL = `    <div
      id="change-role-modal"
      class="lms-fixed-overlay-safe fixed inset-0 z-[60] flex items-center justify-center p-4 hide"
      role="dialog"
      aria-modal="true"
      aria-labelledby="change-role-modal-title"
      aria-hidden="true"
    >
      <div
        class="absolute inset-0 bg-slate-950/65 backdrop-blur-md transition-opacity dark:bg-black/55"
        data-change-role-dismiss
        aria-hidden="true"
      ></div>
      <div
        id="change-role-modal-panel"
        class="lms-modal-surface relative z-10 w-full max-w-[22rem] overflow-hidden rounded-[1.75rem] border border-slate-200/70 bg-white/85 shadow-[0_20px_60px_-12px_rgba(15,23,42,0.2),inset_0_1px_0_0_rgba(255,255,255,0.9)] backdrop-blur-2xl dark:border-white/15 dark:bg-[rgba(15,23,42,0.75)] dark:shadow-[0_12px_48px_rgba(0,0,0,0.45),inset_0_1px_0_0_rgba(255,255,255,0.08)]"
      >
        <div
          class="rounded-[1.5rem] px-5 pt-5 pb-4"
        >
          <div class="mb-4 flex items-start justify-between gap-2">
            <div class="min-w-0">
              <p
                class="text-[0.65rem] font-semibold uppercase tracking-[0.14em] text-primary-600/90 dark:text-primary-400/90"
              >
                User role
              </p>
              <h3
                id="change-role-modal-title"
                class="font-display mt-1 text-xl font-semibold tracking-tight text-slate-900 dark:text-white"
              >
                Change role
              </h3>
              <p class="mt-1.5 text-xs leading-relaxed text-slate-600 dark:text-dark-400">
                Current:
                <span
                  id="change-role-current-label"
                  class="font-semibold capitalize text-slate-800 dark:text-white"
                  >—</span
                >
              </p>
            </div>
            <button
              type="button"
              id="change-role-modal-close"
              class="shrink-0 rounded-xl p-2 text-slate-500 transition-colors hover:bg-surface-hover hover:text-slate-800 dark:text-dark-400 dark:hover:text-white"
              aria-label="Close"
            >
              <svg
                class="h-5 w-5"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
                aria-hidden="true"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M6 18L18 6M6 6l12 12"
                ></path>
              </svg>
            </button>
          </div>

          <input type="hidden" id="change-role-user-id" value="" />

          <p
            class="mb-2 text-[0.65rem] font-semibold uppercase tracking-wide text-slate-500 dark:text-dark-500"
          >
            New role
          </p>
          <div
            class="flex gap-1 rounded-2xl border border-slate-200/90 bg-slate-100/90 p-1 shadow-[inset_0_1px_2px_rgba(15,23,42,0.06)] backdrop-blur-md dark:border-white/10 dark:bg-black/35 dark:shadow-[inset_0_1px_2px_rgba(0,0,0,0.2)]"
            role="radiogroup"
            aria-label="Select new role"
          >
            <button
              type="button"
              class="change-role-segment flex-1 rounded-xl border border-transparent py-2.5 text-center text-xs font-semibold uppercase tracking-wide text-slate-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary-500/50 focus-visible:ring-offset-2 focus-visible:ring-offset-white dark:text-white/65 dark:focus-visible:ring-primary-400/60 dark:focus-visible:ring-offset-dark-950"
              data-change-role-value="student"
              role="radio"
              aria-checked="false"
            >
              Student
            </button>
            <button
              type="button"
              class="change-role-segment flex-1 rounded-xl border border-transparent py-2.5 text-center text-xs font-semibold uppercase tracking-wide text-slate-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary-500/50 focus-visible:ring-offset-2 focus-visible:ring-offset-white dark:text-white/65 dark:focus-visible:ring-primary-400/60 dark:focus-visible:ring-offset-dark-950"
              data-change-role-value="teacher"
              role="radio"
              aria-checked="false"
            >
              Teacher
            </button>
            <button
              type="button"
              class="change-role-segment flex-1 rounded-xl border border-transparent py-2.5 text-center text-xs font-semibold uppercase tracking-wide text-slate-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-primary-500/50 focus-visible:ring-offset-2 focus-visible:ring-offset-white dark:text-white/65 dark:focus-visible:ring-primary-400/60 dark:focus-visible:ring-offset-dark-950"
              data-change-role-value="admin"
              role="radio"
              aria-checked="false"
            >
              Admin
            </button>
          </div>

          <div class="mt-5 flex gap-2">
            <button
              type="button"
              id="change-role-cancel-btn"
              class="flex-1 rounded-xl border border-slate-200/90 bg-white/50 py-3 text-sm font-semibold text-slate-700 shadow-sm transition-colors hover:bg-surface-hover dark:border-white/15 dark:bg-surface-hover dark:text-white/90 dark:hover:bg-surface-hover"
            >
              Cancel
            </button>
            <button
              type="button"
              id="change-role-confirm-btn"
              class="flex-1 rounded-xl bg-gradient-to-b from-primary-500 to-primary-600 py-3 text-sm font-semibold text-white shadow-[0_1px_0_0_rgba(255,255,255,0.2)_inset,0_4px_16px_-2px_rgba(20,95,89,0.45)] ring-1 ring-white/15 transition-[transform,box-shadow] hover:from-primary-400 hover:to-primary-500 motion-safe:active:scale-[0.98]"
            >
              Save
            </button>
          </div>
        </div>
      </div>
    </div>`;
